### ISSUE TITLE
Ask W3C site manager to change description of group

### ISSUE THREAD

**Issue by masinter** [masinter/pdf-data-cg-charter#9]
This issue is about the description of the CG that is in W3C's list of community groups, e.g., if you look for all current CGs or if you do a search.   

I originally put in a very terse 'description' for the CG and said "A charter will be posted soon".

What we need is a paragraph describing the group that will make people want to join. And at least a pointer to the charter.

There is no apparent UI to change the group description except to ask the site manager, so unfortunately that seems necessary.

**Comment by masinter** [comment]
I think we might want to say, the group is for those who want to solve the problem for  those who want to use PDF. I don't want to spend lots of time debating when, if ever, PDF is the right choice.

**Comment by mac2net** [comment]
I think you can change this at the backend. In order to get to the backend, you need to login to the W3 WordPress multisite by using the W3 login where it says "Login" on the admin tool bar on the right side (just to the left of "My W3C Account"). Once logged-in you can get to the back end of the site from the "My Sites" on the left side of the admin tool bar.
At the back end, go to "Pages" and "Posts" from the WordPress admin menu. The Charter is probably a "page". 
I am not 100% sure about this as I am not an admin and other community groups seem to be organised inconsistently.

**Comment by masinter** [comment]
thanks, I've edited the group description, and pointed to the charter.
